### PR TITLE
fix: Remove workaround known API bug

### PR DESCRIPTION
**Pull request by ajtran**
Remove workaround for the known api bug: https://github.com/rollbar/terraform-provider-rollbar/issues/79

as specified in the comment thread in the above issue.

### CODE REVIEW

**Comment by jmcvetta** [comment]
Hi Anthony.  The tests are failing for this PR.  Please make them pass, then request another review.

**Comment by jmcvetta** [comment]
Hi @ajtran - when can I expect an update on this PR?

**Comment by ajtran** [comment]
> Hi @ajtran - when can I expect an update on this PR?

I'll try to get it to you by EOD PST today!

**Comment by ajtran** [comment]
@jmcvetta I've made an update to this PR. All the unit tests now pass. Is it alright to merge without all of the Acceptance test passing?

**Comment by jmcvetta** [comment]
> Is it alright to merge without all of the Acceptance test passing?

No, of course not!  If the _acceptance_ tests are failing, that means the code is _unacceptable_.

Let's take a look at how to debug these failing tests:

The first step is to make sure the full test suite still passes for branch `master`.  This is important to check, in case something about the API changed.  If `master` fails, then the problem is not with the new code.  But if `master` passes, we know the problem _is_ in the new code.

A test run tells me `master` still passes acceptance testing.  So we know the problem is in the new code.  

Next step is to run the acceptance tests for the new branch.  We already know from automated test runs that the suite will fail.  But the UI on Github Actions leaves a whole lot to be desired.  So we want to run the tests locally.  If you're going to work on Go code, I highly recommend using [Goland](https://www.jetbrains.com/go/) IDE.  It just makes everything easier.  

Now let's look at our test failures, in the next comment...

**Comment by jmcvetta** [comment]
When we run the acceptance tests locally, we see more than 10 tests are failing.

image

These tests all fail with the same error message.  However it surfaces at different places in the code.  E.g.:

```
=== CONT  TestAccSuite/TestAccInvitedUserRemoveTeam
    resource_user_test.go:303: Step 1/2 error: Error running apply: 
        Error: 1 Team not found in this account.
```

```
=== CONT  TestAccSuite/TestAccProjectAccessTokensDataSourceNoTokensNoPrefix
    data_source_project_access_tokens_test.go:47: Step 1/1 error: Error running post-apply refresh: 
        Error: 1 Team not found in this account.
```

```
=== CONT  TestAccSuite/TestAccProjectAddTeam
    resource_project_test.go:145: Step 1/2 error: Error running apply: 
        Error: 1 Team not found in this account.
```

And so forth...

**Comment by jmcvetta** [comment]
Let's dig a little deeper.  The errors we're seeing above are coming out of the Terraform acceptance testing harness.  That's why they appear to be coming from different places in the code: that's the [test step](https://www.terraform.io/docs/extend/testing/acceptance-tests/teststep.html) that failed.  

But the fact that we're seeing the same error message over and over again, tells us all these errors (probably) have the same source.

We'll look now at the full debug log for `TestAccProjectAddTeam`, because it's short and easy to understand.  Note the lines beginning with `===` come from Goland IDE not from the output of the tests.

```
=== CONT  TestAccSuite/TestAccProjectAddTeam
5:54PM DBG provider_test.go:85 > Passed preflight check
5:54PM DBG ../client/project.go:203 > Project successfully deleted projectID=451018
5:54PM DBG resource_project.go:228 > Successfully deleted rollbar_project resource projectID=451018
=== CONT  TestAccSuite/TestAccProjectAddTeam
    resource_project_test.go:145: Step 1/2 error: Error running apply: 
        Error: 1 Team not found in this account.
        
        
5:54PM DBG ../client/client.go:45 > Initializing Rollbar client
5:54PM INF resource_project.go:221 > Deleting rollbar_project resource projectID=451022
5:54PM DBG ../client/project.go:186 > Deleting project projectID=451022
5:54PM DBG ../client/client.go:45 > Initializing Rollbar client
5:54PM ERR ../client/client.go:101 >  ErrorResult={"Err":1,"Message":"Team not found in this account."} Status="403 Forbidden" StatusCode=403
5:54PM ERR ../client/team.go:294 > Error listing projects for team error="1 Team not found in this account." teamID=739351
5:54PM ERR ../client/project.go:224 >  error="1 Team not found in this account." project_id=451021
5:54PM ERR resource_project.go:186 >  error="1 Team not found in this account." projectID=451021
    --- FAIL: TestAccSuite/TestAccProjectAddTeam (15.03s)
```

The error first appears at [`../client/client.go:101`](https://github.com/rollbar/terraform-provider-rollbar/blob/3be54711c0c0a8b8f1f29e93d7060564b8b8e847/client/client.go#L101).  Let's look at the block of code containing that line:


```go
// errorFromResponse interprets the status code of Resty response, returning nil
// on success or an appropriate error code
func errorFromResponse(resp *resty.Response) error {
	switch resp.StatusCode() {
	case http.StatusOK, http.StatusCreated:
		return nil
	case http.StatusUnauthorized:
		return ErrUnauthorized
	case http.StatusNotFound:
		return ErrNotFound
	default:
		er := resp.Error().(*ErrorResult)
		log.Error().
			Int("StatusCode", resp.StatusCode()).
			Str("Status", resp.Status()).
			Interface("ErrorResult", er).
			Send()
		return er
	}
}
```

The `ErrorResult` object is created (and logged) when the switch statement falls through to the default.  Meaning the API sent a result this function wasn't expecting, so the function packages that error message in an `ErrorResult` object and passes it back to the caller.

**Comment by jmcvetta** [comment]
This is the really interesting line in the output:

```
5:54PM ERR ../client/client.go:101 >  ErrorResult={"Err":1,"Message":"Team not found in this account."} Status="403 Forbidden" StatusCode=403
```

Here we're seeing the API send a [`403 Forbidden`](https://httpstatuses.com/403) status code; but with a message that clearly indicates this is a Not Found error.  Which is exactly what the workaround you're trying to remove is there to catch.  

The problem, then, is that in some cases the API is still returning `403 Forbidden` when it should be returning a `404 Not Found`.

**Comment by jmcvetta** [comment]
We see then that the API is not yet behaving correctly.  The best course of action is to fix the API so it returns correct status codes.  Until that's done, the workaround cannot be removed.

**Review by jmcvetta — CHANGES_REQUESTED** [review]
Acceptance tests are failing.  See Issue comments for discussion.

**Comment by ajtran** [comment]
Oh. I think I see the issue in the API now. Thank you for the clear write up!! @jmcvetta

One question I had is what is needed when you run the acc tests? Right now, I'm running them in the terminal with the command `make testacc` and I don't see the same output you've described and it seems more tests are failing on my local machine. Also, I've exported the `ROLLBAR_API_KEY` which I believe must be done to run these tests.

**Comment by jmcvetta** [comment]
> I don't see the same output you've described

Just merged a PR to enable debug output from `make testacc`: https://github.com/rollbar/terraform-provider-rollbar/pull/212/files

Note it will only display debug output if tests fail.


> Also, I've exported the ROLLBAR_API_KEY which I believe must be done to run these tests.

Correct.


> it seems more tests are failing on my local machine

Not sure what's up with that.  The API key should be all you need.

**Comment by ajtran** [comment]
Aha. Found it. Finally got the same results.

1) I was on an older version of Terraform 11.x; fixed that.
2) The `ROLLBAR_API_KEY` has to have both `read` and `write` access.

I'll open a PR for the fix in the API and come back to this PR.

**Comment by ajtran** [comment]
@jmcvetta I've merged the following [PR](https://github.com/rollbar/moxapi/pull/573) into the API, so it now returns a 404 in all places when the team cannot be found. This fixes the failing accuracy tests from before. However, there's now a failing check from code climate. Wondering if I could get your review and advice on how to proceed.

**Comment by jmcvetta** [comment]
@ajtran weird - I don't know why CodeClimate failed its check.  When I click on the detail link, CodeClimate says nothing has changed:

image

**Comment by jmcvetta** [comment]
Everything else looks good; and the failed CodeClimate check appears to be a glitch in CodeClimate itself.  So I will go ahead and merge this PR.

**Pull request merged**
